### ISSUE TITLE
Design: tailwind 커스텀 색상 변경 및 기타 수정 작업

### ISSUE THREAD

**Issue by starcradle101** [Team-Detective/tomatoes#16]
## 설명
본 이슈에서는 Tailwind CSS에서 사용하는 커스텀 색상 이름을 피그마 시안 기반으로 변경하고, 기타 수정 작업을 진행할 예정입니다.

## 기대 효과
- 피그마 시안을 기반으로 색상 이름 사용 가능
- README.md 파일 오탈자 수정

## TODO
- [ ] `tailwind.config.ts` 파일 수정
- [ ] `README.md` 파일 수정
- [ ] 커스텀 색상을 사용하고 있는 컴포넌트 클래스 이름 수정
