### ISSUE TITLE
Feat: 공용 버튼 컴포넌트 리팩토링 및 범용성 향상 작업

### ISSUE THREAD

**Issue by starcradle101** [Team-Detective/tomatoes#5]
## 설명
오늘 오전 임시로 생성한 버튼 컴포넌트의 경우 범용성이 부족하고 코드의 개선사항이 발견되었습니다.
본 이슈에서는 해당 버튼 컴포넌트의 범용성을 높이고 코드 구조를 개선하고자 합니다.

## 기대 효과
- props를 기반으로 조금 더 유연하게 버튼 컴포넌트를 사용할 수 있습니다.

## TODO

- [ ] `Button.tsx` 컴포넌트의 구조 분석
- [ ] 하드코딩 처리되어 있는 코드를 최대한 범용적으로 사용 가능하게 분리
- [ ] 버튼 컴포넌트 테스트
